development:
  clients:
    default:
      database: db_development
      hosts:
        - localhost:27017
      options:
  options:

test:
  clients:
    default:
      database: db_test
      hosts:
        - localhost:27017
      options:
        read:
          mode: :primary
        max_pool_size: 1

production:
  clients:
    default:
      database: webmil_db
      hosts: ["<%= ENV['MONGODB_ADDRESS']%>:27017"]
