development:
  clients:
    default:
      database: db_development #ENV['DB_DEVELOPMENT']
      hosts:
        - localhost:27017
      options:
  options:

test:
  clients:
    default:
      database: db_test #ENV['DB_TEST']
      hosts:
        - localhost:27017
      options:
        read:
          mode: :primary
        max_pool_size: 1

production:
  clients:
    default:
      database: webmil_db #ENV['DB_PRODUCTION']
      hosts: ["<%= ENV['MONGODB_ADDRESS']%>:27017"]
